### ISSUE TITLE
Application Error: Exception EAbstractError in module Algodoo_2_1_0-Win32.tmp at 00011F67. Abstract error.

### ISSUE THREAD

**Issue by nikitafun1** [olegos2/mobox#107]
![Screenshot_2024-01-14-16-51-57-499_com termux x11](https://github.com/olegos2/mobox/assets/122173041/bbf5dea9-a615-4ca4-a345-75274020c415)

**Comment by olegos2** [comment]
Try with dynarec preset 3 or 2

**Comment by nikitafun1** [comment]
> Try with dynarec preset 3 or 2

2 preset worked for me, 3 preset when i launching wine shows black screen with X cursor.

How i can boost performance?

**Comment by nikitafun1** [comment]
Thank you. 2 preset worked for me.

**Comment by Praise24-byte** [comment]
Exception EAbstractError in module

setup_guns_gore_cannoli_.tmp at 00011667. Abstract Error.

**Comment by Praise24-byte** [comment]
On mobox emuletor

**Comment by Sanadpalayi** [comment]
![Screenshot_20241018_143324_Winlator](https://github.com/user-attachments/assets/4d748089-f429-4bb3-831a-54cce8098c31)
