### ISSUE TITLE
I got dx12 games to work u made a small mistake.

### ISSUE THREAD

**Issue by KintCark** [olegos2/mobox#12]
U hadvvk3d dll swaped u had 64bit dll in the 32bit folders and 32bit dll in the 64bit folder
In the vk3d.7z  I swaped them and the dx12 games work now.so i uploaded the fix in wemu Telegram. But u can update mobox with this fix.

**Comment by KintCark** [comment]
U accidentally put the vk3d system32 dlls in the syswow64 folder
And u put the vk3d syswow64 dlls in the system32 folder.i downloaded
Vk3d 2.11 and if u look at the file size the syswow64 file size are matching the
X32 folder in the vkd3d 2.11 download. Go download the vkd3d 2.11 from github 
And compare the dll sizes ull see what I'm talking about.

**Comment by olegos2** [comment]
kk, I will add this...
