### ISSUE TITLE
how do I fix this

### ISSUE THREAD

**Issue by Bab1100** [olegos2/mobox#123]
[mobox_log.txt](https://github.com/olegos2/mobox/files/13959683/mobox_log.txt)
Some games won't launch but they work on my pc, my device is poco f3 rooted and using lineageos 20
This is what the log has
------------------------------------------------------------------
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
wineserver: using server-side synchronization.
Failed to open /data/data/com.termux/files/usr/glibc/etc/machine-id, error No such file or directory.
wine: Using setpriority to control niceness in the [-19,19] range
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
Error initializing native libcups.so.2 (last dlerror is libcups.so.2: cannot open shared object file: No such file or directory)
Error initializing native libcups.so.2 (last dlerror is libcups.so.2: cannot open shared object file: No such file or directory)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)

**Comment by olegos2** [comment]
Need more specific information. At least which game you tried to run. Also check readme and enable second option in Debug settings, then send the log

**Comment by Bab1100** [comment]
The game I tried to run was assassin's creed 4 black flag installed from fitgirl repack, the setup didn't run on mobox, so I installed it with my pc and transferred the files to my phone, here's the log with the debug settings
[mobox_log.txt](https://github.com/olegos2/mobox/files/13971390/mobox_log.txt)

**Comment by Bab1100** [comment]
> Need more specific information. At least which game you tried to run. Also check readme and enable second option in Debug settings, then send the log

The game I tried to run was assassin's creed 4 black flag installed from fitgirl repack, the setup didn't run on mobox, so I installed it with my pc and transferred the files to my phone, here's the log with the debug settings
[mobox_log.txt](https://github.com/olegos2/mobox/files/13971390/mobox_log.txt)

**Comment by olegos2** [comment]
0164:warn:module:process_attach Initialization of L"uplay_r1_loader.dll" failed
0164:err:module:LdrInitializeThunk "uplay_r1_loader.dll" failed to initialize, aborting
0164:err:module:LdrInitializeThunk Initializing dlls for L"D:\\Games\\Assassins's Creed 4 - Black Flag\\AC4BFSP.exe" failed, status c0000005

You can try moving your game to E: drive. Also it could be crack issue...
