### ISSUE TITLE
Max Payne 2 long loading time(5-10 min) with first loading screen 

### ISSUE THREAD

**Issue by VR2243** [olegos2/mobox#124]
The game runs pretty smooth 60 fps on Snapdragon 870, so no issues with performance. The only issue i have is that the first loading screen takes about 5 to 10 minutes. Once it loads into menu, the level loading takes about only 10 sec. If it's possible, how can i fix it?

**Comment by olegos2** [comment]
Have you tried moving the game to E: or C: if it's not there?

**Comment by VR2243** [comment]
> Have you tried moving the game to E: or C: if it's not there?

Thanks! That fixed it. Loading time is now less than a minute.
