### ISSUE TITLE
Access violation at address 005E0999

### ISSUE THREAD

**Issue by ONISniperOne** [olegos2/mobox#126]
Tried to install vscode, and I got this error 
![Screenshot_20240117_153058_TermuxX11](https://github.com/olegos2/mobox/assets/128614019/29c29209-8649-4a61-8af0-c3e44a2ea649)

If mobox isn't suited for this program, what are options can I use?

**Comment by olegos2** [comment]
Try to change dynarec preset to 2

**Comment by ONISniperOne** [comment]
> Try to change dynarec preset to 2

Just tried it. This time I'm able to go through the installer (x64, user version and system version). The install progress bar finished and then this popped up

Not access violation anymore but AppUserModel fail. Strange thing is that vscode is in the add/remove program menu but it doesn't show up on the desktop and program menu (I ticked those boxes)
![Screenshot_20240118_012913_TermuxX11](https://github.com/olegos2/mobox/assets/128614019/29ad4749-7381-439a-a6c0-dd846bf84ae2)

**Comment by olegos2** [comment]
Shortcuts won't work, but vscode itself should be already installed. Just go to its directory and try to run it

**Comment by ONISniperOne** [comment]
> Shortcuts won't work, but vscode itself should be already installed. Just go to its directory and try to run it

Found the .exe in its install directory. Double clicked it and nothing popped up. However, when I tried launching the uninstaller.exe, it worked. T.T
