### ISSUE TITLE
D3D9 Display issues and other general tweaks

### ISSUE THREAD

**Issue by Jacobw1oo** [olegos2/mobox#132]
RedMagic 8S ( Snapdragon 8 Gen 2 8 cores, 16GB RAM, Adreno 740 )
Steam: Dxvk 1.10.3 async crashed more than 10 times in row, it can run for short periods of time.
Steam: Dxvk 2.0 async start after 2 crashes, my controls don't work in games. 
![Screenshot_20240118_151811](https://github.com/olegos2/mobox/assets/131918522/25e1904d-588b-4955-9378-597c905c5e18)
Mouse and keyboard do not work at the same time in any game, mostly the keyboard does not work, Skyrim the mouse does not work. No controller work (it is a know bug, i would like to help with.)

Counter-Strike Source 45 FPS with flickering issues 
https://youtu.be/2wqwNiPWRy8

Portal 2 70 FPS with flickering issues 
https://youtu.be/BX-r1ilbNuY

Skyrim had major issues this time, only got 20 FPS, Normally get 40 FPS. 
https://youtu.be/r_M_0Yr_r4U

PS: Hope you all have a great day.

**Comment by olegos2** [comment]
Controls from input bridge should work, except for some games that are not in your list. Xinput is not supported for now, so can't use xinput controls in input bridge

**Comment by Jacobw1oo** [comment]
yes, xinput does not work, know bug that would like to help with. 
The touch controller work mostly, but keyboards and mouse don't work. and what functions do work are no normal. 
I am testing wine 9.0 right now, seems a lot more stable, with steam. lot of little UI issues.

**Comment by GVO72** [comment]
I have the flickering issue in any game that I launch using DXVK and Turnip drivers. If I use VirGL and Wined3d the flicker disappear, but obviously the performance tanks.
Anyone was able to fix flickering using the 8 Gen 2?

**Comment by Jacobw1oo** [comment]
Turnip v6 fixes the flicking issue.
