### ISSUE TITLE
It's showing storage permission denied 

### ISSUE THREAD

**Issue by Oscentury** [olegos2/mobox#137]
![Screenshot_20240119-214931](https://github.com/olegos2/mobox/assets/157144138/51a23bec-2399-4f19-86ec-8542a437d8b6)
It's showing storage permission denied

**Comment by hisham2630** [comment]
> ![Screenshot_20240119-214931](https://private-user-images.githubusercontent.com/157144138/298133519-51a23bec-2399-4f19-86ec-8542a437d8b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODcyMjgsIm5iZiI6MTcwNTY4NjkyOCwicGF0aCI6Ii8xNTcxNDQxMzgvMjk4MTMzNTE5LTUxYTIzYmVjLTIzOTktNGYxOS04NmVjLTg1NDJhNDM3ZDhiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNzU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWU2YjU4N2I4NTEzOGRkN2M2NTZhZjNmNTQzNmQ5ODE4ZDBhZDJlZjAyN2I5MzkxMjFlZTYxMjMzMWQ0ODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D2PqiCQfQHTyPplEYDQ3SooPUM9Sw9qgMGdDV6SfZqI) It's showing storage permission denied

are you on Android 14?
if so run this in termux
pkg install termux-am

**Comment by Oscentury** [comment]
> > ![Screenshot_20240119-214931](https://private-user-images.githubusercontent.com/157144138/298133519-51a23bec-2399-4f19-86ec-8542a437d8b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODcyMjgsIm5iZiI6MTcwNTY4NjkyOCwicGF0aCI6Ii8xNTcxNDQxMzgvMjk4MTMzNTE5LTUxYTIzYmVjLTIzOTktNGYxOS04NmVjLTg1NDJhNDM3ZDhiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNzU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWU2YjU4N2I4NTEzOGRkN2M2NTZhZjNmNTQzNmQ5ODE4ZDBhZDJlZjAyN2I5MzkxMjFlZTYxMjMzMWQ0ODdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D2PqiCQfQHTyPplEYDQ3SooPUM9Sw9qgMGdDV6SfZqI) It's showing storage permission denied
> 
> are you on Android 14? if so run this in termux pkg install termux-am

No Android 13

**Comment by Khang5687** [comment]
For my case, as per these lines of code of the install script [mobox/install.sh](https://github.com/olegos2/mobox/blob/77a1d3dc51aeebac048a3ac0f48da2c19d36895c/install#L10C1-L18C1)

I tried to create a directory: `~/storage/shared` then proceeded with the install and it worked flawlessly!
If you wonder, these are the commands:
```
cd ~
mkdir storage
cd storage
mkdir shared
```
