### ISSUE TITLE
Can't install gog games, they work on box64droid (s23, snapdragon 8 gen 2, turnip drivers)

### ISSUE THREAD

**Issue by leocvf** [olegos2/mobox#14]
I tryed to install 4 diferent gog games and they don't install, other type of installation works
![image](https://github.com/olegos2/mobox/assets/7322274/96407289-641e-4f44-854d-4510120f1c9a)
![image](https://github.com/olegos2/mobox/assets/7322274/7d95be48-3b12-4628-89d4-a42c15875d49)

**Comment by olegos2** [comment]
Change dynarec preset to 3

**Comment by leocvf** [comment]
Just for reference the colonists is a dx11 unity game

**Comment by leocvf** [comment]
no luck here, no setting fix the issue

**Comment by leocvf** [comment]
going to close the issue since gog games can be installed now using dynarec preset 3
