### ISSUE TITLE
I have a question..

### ISSUE THREAD

**Issue by GuilhermeDunkly** [olegos2/mobox#143]
Why is it only possible to use Wine-Esync with Wine-Ge-Custom-8.25?

**Comment by olegos2** [comment]
Only wine ge custom 8-25 was built with patched esync for all users

**Comment by Jacobw1oo** [comment]
Here is a video on how to install Wine 9.0 rc4 with custom esync
https://www.youtube.com/watch?v=NnkDCUVxt3k
