### ISSUE TITLE
Steam has a high chance of crashing everything.

### ISSUE THREAD

**Issue by RebornOfc** [olegos2/mobox#15]
I've downloaded the steam installer and successfully installed it, but once I open it, it has a high change of crashing termux-x11 and termux (they will refresh)

Is it happening because of my phone specs?

Moto g54 - 4GB ram (sadly), Mediatek Dimensity 7020

**Comment by olegos2** [comment]
If termux app is stopped, then it's low memory issue

**Comment by RebornOfc** [comment]
Ok it can be it
