### ISSUE TITLE
Games won't start

### ISSUE THREAD

**Issue by Anonek2002** [olegos2/mobox#155]
Hello ! 
Firstly let me thank you for creating this emulator, it's amazing and the best one as of now. Unfortunately I encountered issue with it on my new device. Not to mention games, even benchmarking tool (EnvMapping DX9) won't start. I tried with dozens of different dynarec settings, disableing esync, dri3 and playing with compatibility settings. I also tried it on different wine containers and version but nothing seems to work. Also, whenever I exit my session and start wine again, a lot of important packaged are missing and I need to verify file integrity. Here is the list of missing/corrupted packages that must be download each time:

Checking md5 for box86-box64-binaries
glibc/bin/box86: FAILED
glibc/bin/box64: FAILED
Checking md5 for glibc-prefix
glibc/var/cache/fontconfig/01be555bce223e9bcb2750153acefc12-le32d8.cache-8: FAILED
glibc/var/cache/fontconfig/01be555bce223e9bcb2750153acefc12-le64.cache-8: FAILED
glibc/lib/libglapi.so.0: FAILED
glibc/lib32/libglapi.so.0: FAILED

In logs there are many errors, the most often occuring ones are:
fixme:nls:init_locale Failed to set LC_ALL to "C.utf8", is the locale supported?
Failed to open /etc/machine-id, error No such file or directory.002c:warn:wineboot:initialize_qpc_features 
Failed to compute TSC frequency, unable to check invariant TSC.0068:warn:mountmgr:run_dbus_loop failed to get system dbus connection: Failed to connect to socket /data/data/com.termux/files/usr/glibc/var/run/dbus/system_bus_socket: No such file or directory007c:err:wineusb:DriverEntry Failed to initialize Unix library, status 0xc0000135.007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000135

And the one that is occuring the most often for different processes is:
warn:system:NtUserEnumDisplaySettings Failed to query L"\\.\DISPLAY1" display settings.

The full debug log file is attached.

My specs:
Android 11
Snapdragon 888
12GB RAM

Any help would be greatly appreciated. 
Thanks in advance!!
[mobox_log.txt](https://github.com/olegos2/mobox/files/14057418/mobox_log.txt)

**Comment by Anonek2002** [comment]
I forgot to mention. 
I've reinstalled mobox many times, but it does nothing :(
Also I tested it on different DXVK/Wine3D settings, but to no avail.

**Comment by looser854449** [comment]
hi,
have you tried exager 5.6 or winlator 5.0??

what's specs of your phone?

**Comment by Anonek2002** [comment]
Hi, I've used Exagear AllMode cache 7.5 and 7.1 both work perfectly fine. I have also tired winlator 4.0 but although it starts normally, whenever I try to open anything requiring 3D rendering it either crashes or don't open at all. Not even games, but simple benchmarking tools. 

My specs:
Snapdragon 888
Adreno 660
12GB RAM
Android 11

My specs:

**Comment by GuilhermeGS2** [comment]
I also can't run any game on mobox or box64, Winlator used to work for me, but since version 4.0 it's also not working anymore. I have a Poco F3 (Snapdragon 870 8GB RAM) on SparkOS 13.5.5.

**Comment by GuilhermeGS2** [comment]
Update: the new experimenta Wow64 version is working for me now, don't know about the OP.

**Comment by Anonek2002** [comment]
That's awesome :)
With the new update I can play some games  if I add it to registry via beth_registry. 
But with it came the new problem, the tfm and whole interface but the desktop disappears often and I need to restart the wine. 
And there is stil the issue of packages going missing after each run.

Could you please tell me of the setting you are using and your phone specs?
I would appreciate it greatly:)

**Comment by GuilhermeGS2** [comment]
I actually didn't need to change anything after installed the wow64 version, it now works with default settings. But in the wine change the turnip to v4 instead of v5, it seems to perform better for me. Some games may require you to use different dynarec settings to run, but usually I use the preset 45, it works with NFS Undegrond 2, NFS Most Wanted, Skyrim LE, Fallout NV, for PES 2013 I need to use the preset 25. I'm also using esync root mode, as I have root on my phone, but the default esync non-root also works. I have a Poco F3 with Snapdragon 870, 8GB of RAM on SparkOS 13.5.5 (Android 13) and N0kernel 15.3.3.

**Comment by Anonek2002** [comment]
UPDATE:

I've just updated my device to Android 12 and it seems the issue is resolved. The libraries still go missing, but it's not a big issue. 
Damn, 60 fps in demanding outside locations in fallout NV kicks different.
Thanks everyone for the support!
