### ISSUE TITLE
Dx11 level 10.0 is required

### ISSUE THREAD

**Issue by RebornOfc** [olegos2/mobox#16]
I try to open a game (The Joy of Creation) and it says Directx11 level 10.0 is required, what can I do?

**Comment by olegos2** [comment]
Virgl?

**Comment by RebornOfc** [comment]
> Virgl?

I tried every VirGL options, it didn't work.

**Comment by olegos2** [comment]
Sadly virgl won't really work with DirectX 10 and 11
