### ISSUE TITLE
InputBridge on Custom Wine (9.0-rc4) not working

### ISSUE THREAD

**Issue by pew1048** [olegos2/mobox#173]
https://github.com/olegos2/mobox/assets/98726618/4f2bfd73-245c-47e0-82d0-7616614254b4

When i use input bridge, it shows up but does not input, how to fix?
Furthermore, it doesn't work in every game

Game name: geometry dash
Device: samsung note 20 ultra (adreno 650)

**Comment by Roy0002** [comment]
How did u get wine9?

**Comment by pew1048** [comment]
on youtube video, currently its deleted
