### ISSUE TITLE
Just Cause 2 runs badly and bugged 

### ISSUE THREAD

**Issue by sidaodomorro** [olegos2/mobox#193]
I`m trying to play just cause 2 but the game has low fps and it keeps flickering on my poco f5, it should run with no problems but its worst than some sd 600 and 700 ,  limiting the fps to 30 improves , but flickering desappears only when fps is extremely stable , when fps stutter the game starts flickering again, i tried many dynarec sets, but nothing solves my problems
Edit:  i made a video to show the error https://youtu.be/o6T3K7tPXF8?feature=shared

![Screenshot_2024-02-11-01-59-09-204_com termux x11](https://github.com/olegos2/mobox/assets/117696701/7a72cf45-180f-4d98-b0b7-9ee7799ff899)

**Comment by olegos2** [comment]
Turnip a7xx issue. Won't be fixed until turnip a7xx gets better

**Comment by sidaodomorro** [comment]
> Turnip a7xx issue. Won't be fixed until turnip a7xx gets better

Oh ok , thank u
