### ISSUE TITLE
Compatibility with Exynos CPU - BUG ON BOOT

### ISSUE THREAD

**Issue by VinZo00** [olegos2/mobox#196]
### **Problem**
I successfully installed mobox with termux and termux:11 on my Galaxy S22 Ultra, and after configuring termux:11 when I start Wine I have this screen where only the cursor appears but not the start button below. I tried different configurations within wine but none of them led me to an effective solution. I have also used more updated Termux:11 versions, tried restarting the emulator and clearing the cache. At this point I don't know if it's a problem with the Exynos CPU with Xclipse GPU, because when trying on OnePlus 6 there are no problems (Snapdragon 845 / Adreno 630).

**Device**
S22 ULTRA
CPU: Exynos 2200
GPU: Xclipse 920
Android version: 14

**Screenshot**
![Screenshot_20240211_130845_TermuxX11](https://github.com/olegos2/mobox/assets/91703888/91cf56ee-e880-4099-a240-ef72147b7eeb)

**Mobox Log**
[mobox_log.txt](https://github.com/olegos2/mobox/files/14232464/mobox_log.txt)

**Comment by olegos2** [comment]
Could be termux-x11 issue or gpu drivers issue

**Comment by olegos2** [comment]
Try to do these steps:
Open in editor file /data/data/com.termux/files/glibc/opt/scripts/start-tfm.
You can do this with nano:
```nano /data/data/com.termux/files/glibc/opt/scripts/start-tfm```
Then search for `termux-x11 :0` in this script (Ctrl+W). And replace it with `termux-x11 :0 -legacy-drawing`. Save script and test if that works.

**Comment by VinZo00** [comment]
> Try to do these steps: Open in editor file /data/data/com.termux/files/usr/glibc/opt/scripts/start-tfm. You can do this with nano: `nano /data/data/com.termux/files/usr/glibc/opt/scripts/start-tfm` Then search for `termux-x11 :0` in this script (Ctrl+W). And replace it with `termux-x11 :0 -legacy-drawing`. Save script and test if that works.

Thank you! Problem solved! :)
