### ISSUE TITLE
BioShock (2007) freezes at Welcome to Rapture loading screen

### ISSUE THREAD

**Issue by Gamelover7825** [olegos2/mobox#2]
When I ran BioShock using DXVK 1.x.x-2.x.x it started only in DX9 mode but crashed after the BioShock loading screen.

When I ran BioShock using DXVK 0.96 it started only in DX10 mode but only the intro level is playable. The game freezes up at the Welcome to Rapture loading screen.

Redmi Note 9 Pro 6/128 (Snapdragon 720G)
Xiaomi Pad 5 6/256 (Snapdragon 860)

Winlator AFEI 1.1.14 is the only emulator which allows to play that game from start to end on my devices.

**Comment by olegos2** [comment]
Try to change dynarec settings, maybe preset 2, 43 or 434

**Comment by olegos2** [comment]
Stale
