### ISSUE TITLE
Portal 1 flashing models

### ISSUE THREAD

**Issue by B1u-J** [olegos2/mobox#209]
I am currently playing portal 1 and everything is working but there is a fairly huge problem: The models / walls are flashing like crazy. The 2d elements are just fine but the second the 3d comes in its like a colorful strobe light. I am using an s24+ with a snapdragon 8 gen 3 on android 14, using the new experimental wow64 version of mobox.

**Comment by olegos2** [comment]
Turnip issue. Will be fixed at some point, hopefully

**Comment by olegos2** [comment]
For now you need to limit fps in DXVK settings to 30
