### ISSUE TITLE
Not working properly on Android 14

### ISSUE THREAD

**Issue by wang6662002** [olegos2/mobox#23]
show :Can't open display :0

**Comment by Shrn744** [comment]
After trying many tricks update 

I found  working  android  14 mobox 

After install mobox 

Exit termux 
Enter again 
Type - 
"Pkg update termux-x11-nightly"

After update open mobox 
It working  one ui 6 android  14 Samsung f23 5g

**Comment by wang6662002** [comment]
Yes, it is working properly. in use

After pkg install termux x11 nightly

> After trying many tricks update
> 
> I found working android 14 mobox
> 
> After install mobox
> 
> Exit termux Enter again Type - "Pkg update termux-x11-nightly"
> 
> After update open mobox It working one ui 6 android 14 Samsung f23 5g

Yes, it is working properly. in use
After pkg install termux x11 nightly
Thanks a lot

**Comment by Shrn744** [comment]
Oh I mistake a big 

I  want to type pkg install 
And I type pkg update 
But this works 💪

**Comment by ABEKE01** [comment]
Здравствуйте, Доброй ночи, у меня телефон OnePlus Ace Pro 10T у меня было система андроид 13 всё работало, но сейчас после обновление системы андроид 14 не работает, в смысле я удалил mobox после обновления системы андроид "Хотел заново установить" думал, типа ФПС прибавится 😄 но не хочет установится обратно, и теперь вот этот надпись Storage permission denied заеб*ла уже "сорри за мат" 😁 разрешение приложению предоставил всё там разрешено, но не устанавливается, как исправить?

За ранее спасибо ✊

**Comment by ABEKE01** [comment]
И кстати у меня Snapdragon 8 Plus Gen 1 и оперативный память 16gb постоянный память 256gb, и вот у меня вопрос я блин всё пробовал Exagear, Exagear Jataros, Termux box, Termux box OlegOs, Mobox, и т.д но у всех был малый ФПС, Assassin's Creed 15fps Batman Arkham City 8-13fps left4dead 9-14fps а GTA 4 вообще беда 5-10fps а у меня телефон мощный, и прикол в том, что я посмотрел в утубе у людей со Snapdragon 860 ФПС у ГТА 4 20-25 как так то? Или я рукажоп или эмулятор сырой, но я тоже не мастер конечно по программе, но я всё по инструкции установил

**Comment by ABEKE01** [comment]
У них там на утубе который я заметил оперативки мало было 6-8gb а у меня аж 16gb больше чем Samsung Galaxy S23 ultra, это выше крыши блин, как так то? Кстати у меня ещё оболочка Oxygen OS 14v я думаю это не мешает на эмуляцию по тому что это оболочка на подобии MIUI и т.д, я все настройки там пробовал, драйвера и т.д, и даже драйвера для Mali тоже пробовал 😁короче не знаю в чем прикол 😁 если кто то может помочь отзовитесь пожалуйста

Буду благодарен, за ранее спасибо ✊

**Comment by ABEKE01** [comment]
> О, я ошибаюсь, большая
> 
> Я хочу ввести pkg install И я набираю pkg update Но это работает 💪

Здравствуйте, Доброй ночи, 
Спасибо Брат ✊ вы мне очень помогли
OlegOs Mobox снова работает на андроид 14 
Не мог установить, вводил ваш код, теперь установился, Спасибо большое 🤝 от души ✊

**Comment by ABEKE01** [comment]
> О, я ошибаюсь, большая
> 
> Я хочу ввести pkg install И я набираю обновление pkg Но это работает 💪

Извините, к вам у меня вопрос есть

У меня телефон OnePlus Ace Pro 10T Ram 16gb Rom 256gb Processor Snapdragon 8 Plus Gen 1 оболочка Oxygen OS v13

А в игре fps не очень, даже на Snapdragon 865 fps нормальный, в YouTube видел 
Мой телефон в двое мощный, как так?

**Comment by ABEKE01** [comment]
> О, я ошибаюсь, большая
> 
> Я хочу ввести pkg install И я набираю обновление pkg Но это работает 💪

За ранее спасибо ✊
