### ISSUE TITLE
K-lite not install

### ISSUE THREAD

**Issue by GuilhermeDunkly2** [olegos2/mobox#260]
Erh...
![Screenshot_20240301-182625_TermuxX11](https://github.com/olegos2/mobox/assets/160188999/0d322c40-760e-40e5-9bc5-74722acaf8f9)
[mobox_log.txt_wineboot.txt](https://github.com/olegos2/mobox/files/14466162/mobox_log.txt_wineboot.txt)
[mobox_log.txt](https://github.com/olegos2/mobox/files/14466163/mobox_log.txt)

**Comment by inguna87** [comment]
Try setting dynarec to 2

**Comment by GuilhermeDunkly2** [comment]
Ok
