### ISSUE TITLE
Keyboard and mouse 

### ISSUE THREAD

**Issue by Arsalvean** [olegos2/mobox#270]
Can we connect keyboard and mouse with mobox..??

**Comment by Sbou73** [comment]
Tested bluetooth keyboard and it's ok

**Comment by Jacobw1oo** [comment]
Technically yes, Here is my previous post: https://github.com/olegos2/mobox/issues/169

**Comment by Jacobw1oo** [comment]
All my games start and run thought steam (which has lots of issues running)
I cant get Just Cause 2 to play at the moment, GTA 4 should start and you got a 50/50 on if the controls are playable.

**Comment by Arsalvean** [comment]
Bro I don't  have steam account..& app
I Just download the setup just cause 2 install and play
It's pretty good 45 30 fps..on s23 ultra sd 8 gen 2 
And my input bridge is working good with my controller..but now I want play on keyboard mouse

**Comment by Jacobw1oo** [comment]
That is great, you phone should have native support for the mouse and keyboard driver. Their is a good chance it will work, mouse will probably have bounding issue (where mouse will hit edge of screen and the look view will stop).

**Comment by Sbou73** [comment]
> Bro I don't have steam account..& app I Just download the setup just cause 2 install and play It's pretty good 45 30 fps..on s23 ultra sd 8 gen 2 And my input bridge is working good with my controller..but now I want play on keyboard mouse

Games recognise your gamepad on mobox?

**Comment by Arsalvean** [comment]
Bro how to check its support or not...??

**Comment by Arsalvean** [comment]
> Games recognise your gamepad on mobox?

With 3rd party app...input bridge I setup buttons
By self & and its work..

**Comment by Arsalvean** [comment]
![Screenshot_20240304_225307_InputBridge.jpg](https://github.com/olegos2/mobox/assets/162111559/7a4fe02c-ea61-4153-bff5-8d8f4cfbe6bf)

**Comment by Arsalvean** [comment]
![Screenshot_20240304_225313_InputBridge.jpg](https://github.com/olegos2/mobox/assets/162111559/731c78a1-043f-47a7-b600-bbf5c58c69d9)

**Comment by Arsalvean** [comment]
![Screenshot_20240304_230848_Gallery.jpg](https://github.com/olegos2/mobox/assets/162111559/ed4e8bd8-7e66-4bc5-bbc7-4198ce64cd5c)

**Comment by Arsalvean** [comment]
![Screenshot_20240304_230848_Gallery.jpg](https://github.com/olegos2/mobox/assets/162111559/04cd3a06-330d-4ccc-982c-19bc702f925f)
