### ISSUE TITLE
Gta 4 problem 

### ISSUE THREAD

**Issue by Arsalvean** [olegos2/mobox#277]
![Screenshot_20240305_174855_TermuxX11.jpg](https://github.com/olegos2/mobox/assets/162111559/d893d70e-f067-45ef-90dd-db0b56ddab15)

Not getting open..!! need help
I download the game..its 11.80 Gb
RaR file..when I open its already installed game..and now its not working 😕

**Comment by Rachitram** [comment]
Yes me same not opening
