### ISSUE TITLE
Cant Cofigure when start Mobox wow64 version

### ISSUE THREAD

**Issue by DarkBringgX** [olegos2/mobox#282]
Maybe someone in here know how to fix " Cannot configure " when I want to start wine on Mobox??

![Screenshot_2024-03-07-18-14-32-499_com termux](https://github.com/olegos2/mobox/assets/71298886/b714de48-468e-488b-a94a-4fc34b70fe6a)

**Comment by PlaindWater** [comment]
Having the same problem, did u fix it? please help!

**Comment by 1852723973** [comment]
我也是，解决了踢我一脚
