### ISSUE TITLE
storage permission denied

### ISSUE THREAD

**Issue by RiverNety** [olegos2/mobox#3]
![Screenshot_20231204-185154_Termux](https://github.com/olegos2/mobox/assets/89873015/8d2b0b37-8494-4183-b3ec-ffb8e94cc2c7) it didnt prompt to access storage, but I have it allowed in app settings.  Using a mi pad 5 with A14 custom rom

**Comment by RiverNety** [comment]
Nvm got to fix it by running pkg install termux-am

**Comment by StigTrooper** [comment]
Couldn't fix mine with pkg install termux-an either.
Help please

**Comment by MatejMagat305** [comment]
I only try to seek solution, you can try put `termux-setup-storage`, then `ls` when you will be able to move into/from storage/download, then I don`t know,, but if not you can try seek in android app setting permision for termux and give storage permision to termux ...
