### ISSUE TITLE
Need Drictx 

### ISSUE THREAD

**Issue by Arsalvean** [olegos2/mobox#307]
Someone give me drictx Please...need help

**Comment by Saikatsaha1996** [comment]
> Someone give me drictx Please...need help

Already included

**Comment by Arsalvean** [comment]
![Screenshot_20240319_191527_TermuxX11.jpg](https://github.com/olegos2/mobox/assets/162111559/31c8eb34-aaf6-427c-9b24-1c4af09edd6e)

**Comment by Arsalvean** [comment]
This is the problem..

**Comment by Saikatsaha1996** [comment]
> > Already included
> 
> Look brother this the problem

Copy game to ```C``` drive

**Comment by Arsalvean** [comment]
> Copy game to ```C``` drive

Look at this gta 4


![Screenshot_20240319_192420_TermuxX11.jpg](https://github.com/olegos2/mobox/assets/162111559/5f38e2af-81fa-4a24-8244-0ac688b952fd)
