### ISSUE TITLE
Add support for controllers natively for rooted devices with this linked solution

### ISSUE THREAD

**Issue by BlazingFlames6073** [olegos2/mobox#314]
Here it is

https://www.reddit.com/r/EmulationOnAndroid/comments/18xtve8/problem_solved_connect_your_game_controller_via/?rdt=65063

I was able to get my controllers working on box64droid though I failed to get them remapped. I can't even get them working on mobox because mobox doesn't provide access to a terminal

If you need the anti.deb file(I don't think so), it's linked on the YouTube channel this person(his own link has expired) from reddit learned the solution from. Here's the video with the link in the description

https://youtu.be/lcG1FII4iIM

Thanks. I would also appreciate if you could add a easy way to map the controllers if you add native controller support for rooted devices.

**Comment by olegos2** [comment]
No termianl, no apt, no xinput
