### ISSUE TITLE
[feature request for both mobox and termux-box] Make turnip part of "turnip zink" optional

### ISSUE THREAD

**Issue by sa1672ndo** [olegos2/mobox#34]
All modern malis or xclipse gpus has vulkan 1.3 support, which allows them to run zink WITHOUT turnip. So the question is, why do you force us to use the crappy virgl, when we can easily run zink with dxvk at the same or even better fps than adenos???

**Comment by sa1672ndo** [comment]
This will also allow adreno users to use root turnip drivers to replace their system driver with turnip that's newer than the one bundled in with the emulator, without the need for you to add the drivers yourself.

**Comment by olegos2** [comment]
System driver can't be used in glibc currently, it can't be done just by removing turnip
