### ISSUE TITLE
bug: mobox crashes when Launched while termux on landscape

### ISSUE THREAD

**Issue by Tempaccnt** [olegos2/mobox#345]
Hello there,

I just noticed an issue. although it's not that bad, I just wanted to share it with the developer in case he wants to fix it.

when Launching mobox with termux on landscape, mobox crashes with the following error:
Can't make sub-window at (4,3), size (1,116).

it can also happen if you switch to landscape while being on mobox menu just before starting wine.

**Comment by olegos2** [comment]
There's not enough space for mobox menu with landscape + software keyboard
