### ISSUE TITLE
Device freeze for a few seconds then reboot

### ISSUE THREAD

**Issue by hisham2630** [olegos2/mobox#35]
Hi
after installing mobox I start mobox by typing mobox in termux
after that i select start wine, when wine starts to install things device will freeze for like 15 secs then reboot.
i tried to reinstall mobox multiple times but same problem.
also I checked packages from settings and it's fine.

device: Xiaomi 13 ultra, snapdragon 8 gen2, android 13.

**Comment by nimade2333** [comment]
I have a friend who also had the same problem. The device is redmi k60 8gen2.

**Comment by hisham2630** [comment]
> I have a friend who also had the same problem. The device is redmi k60 pro 8gen2.

Well i checked that i have teemux v 119 installed then i went a head and uninstall it.
then downloaded the termux v 118 from fdroid , the mobox works fine and there's no freeze.
