### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by balintTheDevX** [olegos2/mobox#352]
![Screenshot_20240412_191115_TermuxX11](https://github.com/olegos2/mobox/assets/152019279/0caef98a-1e3a-4b3e-90bf-bc0d9964b9ea)

**Comment by brawl82** [comment]
![IMG_20240414_084043_020](https://github.com/olegos2/mobox/assets/84627562/5a1e81e5-3735-4752-845b-0b767fd25623)
I had this, I already solved the problem

**Comment by balintTheDevX** [comment]
How

**Comment by brawl82** [comment]
![Screenshot_2024-04-15-07-47-26-80_84d3000e3f4017145260f7618db1d683](https://github.com/olegos2/mobox/assets/84627562/c91f7f03-d34a-4a3b-b085-ce8d76d6ce3e)
![Screenshot_2024-04-15-07-47-33-44_84d3000e3f4017145260f7618db1d683](https://github.com/olegos2/mobox/assets/84627562/04a7b39e-c0a5-45d5-9198-7ca9cb295744)
It was set to 1, 0 was needed, so I solved my problem 💀. I solved this problem for 4 days

**Comment by balintTheDevX** [comment]
![Screenshot_20240415_202800_TermuxX11](https://github.com/olegos2/mobox/assets/152019279/b5788ded-5efc-4f89-b15d-7927bf94a28b)
![Screenshot_20240415_202809_TermuxX11](https://github.com/olegos2/mobox/assets/152019279/01c6bb83-b3d9-42cb-b9bb-86cec1c7f961)

https://github.com/olegos2/mobox/assets/152019279/e61bceb4-cbb8-4462-bc6c-0eaa570a44ca

I tried but its still says about directX 9.0C and when I changed  smth when I clicked on a exe its not load
