### ISSUE TITLE
Help i cant run games on mobox 

### ISSUE THREAD

**Issue by balintTheDevX** [olegos2/mobox#356]
![Screenshot_20240415_202800_TermuxX11](https://github.com/olegos2/mobox/assets/152019279/863734ce-feda-4bad-aea9-670b06a6b354)
![Screenshot_20240415_202809_TermuxX11](https://github.com/olegos2/mobox/assets/152019279/3abc25ed-ccb8-4d13-9a5b-0ec4b49f4e1e)

Uploading mobizen_20240415_202720.mp4…

**Comment by balintTheDevX** [comment]
Uploading mobizen_20240415_202720.mp4…

**Comment by balintTheDevX** [comment]
The games its not load

**Comment by balintTheDevX** [comment]
Someone??

**Comment by balintTheDevX** [comment]
Uploading mobizen_20240415_202720.mp4…

**Comment by brawl82** [comment]
![Screenshot_2024-04-15-23-24-49-99_84d3000e3f4017145260f7618db1d683](https://github.com/olegos2/mobox/assets/84627562/c58e8520-177d-41a4-a1c3-3f1a8bd3d0a8)
Try it, it might help

**Comment by balintTheDevX** [comment]
![Screenshot_20240416_184042_TermuxX11](https://github.com/olegos2/mobox/assets/152019279/a4a16b45-a142-485d-a3fd-b56b325181db)
Black Screen Problem
