### ISSUE TITLE
Android 14 permission denied problem but I give the permission 

### ISSUE THREAD

**Issue by Xsparkjimmy** [olegos2/mobox#37]
ANDROID 14 permission denied problem but I give the permission PLEASE solve the problem

**Comment by QstTheDuck** [comment]
what permission? "the permission" isn't really usefull

**Comment by Xsparkjimmy** [comment]
> what permission? "the permission" isn't really usefull

I'll send a screenshot then you understand
U R I'd

**Comment by sbrader** [comment]
> what permission? "the permission" isn't really usefull

Storage permission denied even though ive gave all permissions
![Screenshot_20231219_232500_Termux](https://github.com/olegos2/mobox/assets/28980018/2445fb71-83b0-4634-a382-0fdb191629e1)
![Screenshot_20231219_232506_Permission controller](https://github.com/olegos2/mobox/assets/28980018/2a69dfc8-f395-4f27-96bd-c5856993e36d)

**Comment by sbrader** [comment]
> ANDROID 14 permission denied problem but I give the permission PLEASE solve the problem

I found the fix from reddit enter this command on termux fixed it for me chmod 400 $PREFIX/libexec/termux-am/am.apk
