### ISSUE TITLE
GTA 4 doesnt open

### ISSUE THREAD

**Issue by AndriiK417** [olegos2/mobox#370]
When I try to launch GTA 4, it doesnt do anything. I tried to change everything from Dynarec to Wine and Turnip settings ,any changes

**Comment by reda1919** [comment]
Hello 
Try to customize your dynarec settings to 418 and primary cores to 4 processors. I hope it fixes the problem

**Comment by AndriiK417** [comment]
> Hello Try to customize your dynarec settings to 418 and primary cores to 4 processors. I hope it fixes the problem

Thx, but I already fixed it by enabling compatibility mode

**Comment by reda1919** [comment]
Oh ok hhhhh
