### ISSUE TITLE
Can mobox be used without any connection？

### ISSUE THREAD

**Issue by Discovererian** [olegos2/mobox#371]
I turned off WiFi and data of the phone, then opened mobox. However,the termux-x11 app just showed "not connected". It works properly when the phone is connected to WiFi.
I modified the "start-tfm" and got the termux-x11 dispalyed,but it worked not properly and the audio config of winecfg didn't recognise any sound driver.I launched a game and a messagebox popped up said "EAGLS.DLL error".
I'd appreciate it if anyone can explain the reason or know how to use mobox without any connection.

**Comment by CmbRDevMx** [comment]
> If you do not want to turn off your internet connections such as `WIFI` OR `DATA` You can run the following command in termux:
- This starts mobox skipping updates 
```
bash $PREFIX/glibc/opt/scripts/mobox_menu
```
This replaces the default command that we use every day which is `mobox`

**Comment by Discovererian** [comment]
> > If you do not want to turn off your internet connections such as `WIFI` OR `DATA` You can run the following command in termux:
> - This starts mobox skipping updates 
> ```
> bash $PREFIX/glibc/opt/scripts/mobox_menu
> ```
> This replaces the default command that we use every day which is `mobox`

Thanks,but I mean I "want" to turn off my WiFi and data to use mobox cause I want to play it "totally offline" without any wireless connection.The biggest problem is there no connection and display in x11 app and some drivers not properly loaded when offline.

**Comment by Discovererian** [comment]
A barely satisfactory solution was found.
just turn on the Mobile hotspot and it will work properly.I think there must be something to do with AP.
