### ISSUE TITLE
Mobox wow64

### ISSUE THREAD

**Issue by Asket555** [olegos2/mobox#379]
Will Mobox wow64 continue to be developed or will there be no more updates?

**Comment by olegos2** [comment]
Mobox wow64 will be continued, but as a new project. I think the new project will be announced in couple months.

**Comment by Asket555** [comment]
Look forward to. It would be great if the new project would support controllers in both Xinput Brige and Winlator where games do not support a controller.
P/S Good luck and easy solutions to problems.

**Comment by Asket555** [comment]
Look forward to. It would be great if the new project would support controllers in both Xinput Brige and Winlator where games do not support a controller.
P/S Good luck and easy solutions to problems.
