### ISSUE TITLE
Thoughts on Mobox edge

### ISSUE THREAD

**Issue by Jacobw1oo** [olegos2/mobox#389]
I hope it is real, it would make sense as an evolution to mobox. If It comes out, I would be happy to make videos about it. Mobox being the only windows emulator that works for my device. 

Good luck olegos2, I would be happy to support.

My YouTube https://m.youtube.com/channel/UCQXYWOgWV864kHn9bUqq8SQ

**Comment by jaycore** [comment]
Is olegos2 created mobox edge?

**Comment by MihaiRO1234** [comment]
> Is olegos2 created mobox edge?

Mobox edge its official..but its not released yet...i think this summer will be release.

**Comment by alfa005pro** [comment]
cool
