### ISSUE TITLE
Permission to use mobox explorer wine in personal project

### ISSUE THREAD

**Issue by Alex460k** [olegos2/mobox#392]
Hello,
I am currently working on creating a new emulator for personal use and I was considering publishing it online. I wanted to let you know that my script makes use of the Mobox explorer,  that you developed. Specifically, my script launches the Mobox explorer without running the entire desktop environment, instead only displaying the section where drives are visible. Here is a photo to give you a better idea of what I mean.
I wanted to reach out to you to ask for your permission to use and post my script on GitHub. I will not be publishing your entire repository, only my own script, but it will utilize the Mobox explorer. If you have any questions or concerns, I would be happy to discuss them with you.
You can reach me on Telegram at t.me/Deathghostr. Thank you for your time and I look forward to hearing from you.
Best regards,
Deathghost
![Screenshot_20240504_133658_TermuxX11](https://github.com/olegos2/mobox/assets/123093774/2ac42670-c344-4116-ab75-1244a10680f4)

**Comment by genrogameryt** [comment]
esse projeto tem cara do boxsuer emulator estranho

**Comment by Alex460k** [comment]
Well it was my idea from beginning but i deleted it then he copied mine then just posted it. But itll be an app like winlator so ig it will be better than boxsuer

**Comment by genrogameryt** [comment]
voce esta sabendo das tretas que estão ocorrendo com o olegos  e uma galera ai virus no mobox sabotado
