### ISSUE TITLE
7+gen2

### ISSUE THREAD

**Issue by Belorr** [olegos2/mobox#4]
What is best settings for snap 7+gen2? 
Oblivion: mobox 7-10fps, termux-box 30-40fps
Fallout NV: mobox don't starting, termux-box 30-40fps
Gothic2 Chronicles of Myrtana: mobox don't starting, termux-box 15-30fps

**Comment by olegos2** [comment]
not working games issues are known and will be fixed. Oblivion has low fps due to missing codecs. Both problems have one solution...
