### ISSUE TITLE
[OFFTOPIC] Mobox logo is not fully visible in light mode

### ISSUE THREAD

**Issue by nerdydumbykier** [olegos2/mobox#40]
Hello, I know that this might be offtopic but the `mobox` logo is not fully visible when in light mode. You can see the termux logo but the white flame is not visible.

Dark Mode
![Screenshot_2023-12-15-19-26-52-788_org mozilla fenix-edit](https://github.com/olegos2/mobox/assets/121624727/75733d04-b203-430b-be80-d9a3b45bb8e3)

Light Mode
![Screenshot_2023-12-15-19-25-58-338_org mozilla fenix-edit](https://github.com/olegos2/mobox/assets/121624727/80cb3b7e-67e2-4e34-bc6d-434ca8387f19)

**Comment by olegos2** [comment]
Should be better now when readme logo updates
