### ISSUE TITLE
Cannot configure. See /sdcard/mobox_log.txt_wineboot.txt

### ISSUE THREAD

**Issue by GuilingQiyu** [olegos2/mobox#481]
> Redmi Note 12 Turbo
> Snapdragon 7+Gen2

When Starting Wine,Reporting:
`Cannot configure. See /sdcard/mobox_log.txt_wineboot.txt`

This is the text:
> taskset: failed to set pid 12545's affinity: Operation not permitted

**Comment by ImInfler** [comment]
Whats the solution?
