### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by LNIN786** [olegos2/mobox#65]
Please give us app with out trojen and malware, when i install input bridge app my system security check after installation says immediately uninstall this app riskware,so i check this app by numbers of antivirus software all that says Trojan, malware, malicious activity.i think this much virus why not check termex too but termex doesn't have any virus but termex 11 have Trojan, please make seperate single app of your own without virus like this,i'm not rich so the only way to play pc games through my mobile only so please make your own app without virus like this
![Screenshot_2023-12-31-06-19-51-44_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/olegos2/mobox/assets/133242050/989a6dae-80ce-433c-8a6c-ad1c708a7c93)

**Comment by GrigoryNot2** [comment]
> ...  my system security check after installation says immediately uninstall this app riskware,so i check this app by numbers of antivirus software all that says Trojan, malware, malicious activity.i think this much virus why not check termex too but termex doesn't have any virus but termex 11 have Trojan...

Ты утверждаешь, что из всех сотен людей, которые по всему миру скачивают здесь эти приложения, а некоторые из них даже просматривают исходный код этих приложений и вносят модификации, только ты, с помощью свой не названной системы охраны обнаружил трояны и вирусы? 
И у тебя не появляются подозрения к твоей системе охраны?

**Comment by LNIN786** [comment]
Sorry bro I'm not saying that way,I'm saying if you can give that emulator
this form from some coding,I'm sure you must able to built this all
features in single app,not depend other apps like termex,and also it's not
any unamed antivirus I used virus total

**Comment by LNIN786** [comment]
I'm not questioning about all three apps termex isn't vulnerable,i said input bridge app and termex 11 only if you doubt me please check those apps using virus total, 'virus total using numbers of antivirus software to scan a single app',I'm not saying anything they provided in original termux app,you know input bridge is also used in exagear also it's an another app not from our mobox developer,the total mobox setup is in original termux,termux 11 job is to convert and show the downloaded file and our own system like windows and input bridge is used for onscreen controler,so I ask why we use input bridge and termux,i trust the developer can able to built there own app named mobox it's self without other third party app help

**Comment by Fernand607** [comment]
So is there a virus or not?

**Comment by LNIN786** [comment]
Yes it's have virus,you also check this apps using virus total app or web
site by selecting them from your download directory

**Comment by Fernand607** [comment]
What's the use of him then?

**Comment by Fernand607** [comment]
Harm*

**Comment by LNIN786** [comment]
Bro doesn't make sense how i authored thread,I am ordinary people not an
hacker

**Comment by GrigoryNot2** [comment]
> Bro doesn't make sense how i authored thread,I am ordinary people not an hacker

Что ж, похоже ты, как не специалист, вооружившись одним только virustotal раскрыл вселенский заговор. Мы рекомендуем тебе удалить этот опасный код и больше к нему не возвращаться.

Termux-x11
![Screenshot_20240103-224213_Edge](https://github.com/olegos2/mobox/assets/65012726/c44b1e6a-de12-45ff-acfb-330a0af137d6)

Input_bridge
![Screenshot_20240103-224408_Edge](https://github.com/olegos2/mobox/assets/65012726/77cb21ed-cc3d-4212-b11b-ce6d333912f0)

 Лично мне достаточно того, что несколько проверенных мной в реальных многолетних боях антивирусов, таких как Dr web, Kaspersky, и eset-nod32 не увидели никаких угроз. Сработали в основном какие-то безымянные антивирусы и Microsoft defender, которые используют дополнительные базы данных с классификациями угроз. Эти приложения работают с перехватами данных других процессов и конечно же они будут использовать некоторые функции перехвата, как трояны. Но это не значит, что они воруют историю просмотренного тобой порно из твоего браузера и отправляют её злым хакерам.

**Comment by GrigoryNot2** [comment]
> So is there a virus or not?

Я думаю, что нет

**Comment by LNIN786** [comment]
don't talk to me like that,I'm not afraid of that shitty reason like porn
history,I'm poor my smartphone also doesn't good to run heavy games,but
atleast I want to run low end pc games,if i doesn't want this emulator,why
I give my suggestion?,I only asked them to create a single app to
emulate,not do depand on termex and other two apps,so they create a app
from scratch I'm sure they can able to create a unharmable app like
skyline, Citra.think in my perspective, working for daily wages but the pay
doesn't cover your family needs,so the guy like me careful about everything
it's usual,but my thirst and eagerness for gaming doesn't fade or go
away,so I ask this app creator to make a single app named mobox without
virus

**Comment by GrigoryNot2** [comment]
> ... so I ask this app creator to make a single app named mobox without virus

Если ты внимательно изучишь это приложение, ты можешь увидеть, что группа разработчиков и так объединила почти десяток приложений, которые были модифицированы и облегчены для производительности. При этом они сохранили возможность для пользователей использовать свои компоненты, которые им хочется и настраивать их очень гибко. Мы (сообщество) тоже тестируем и ищем пути решения проблем, с которыми мы столкнулись, но обсуждаем это на других площадках, таких как reddit и 4pda, что бы не создавать здесь свалку. Многие из нас тоже не богаты и работаем за зарплату. У меня лично телефон 2019 года, который я выкупил 3 года назад после ремонта. Например мне не хотелось бы, что бы этот проект превратился в монолитную сборку без возможности настраивать его так гибко, что бы потом ждать решения мелких возникающих проблем разработчиком в течении нескольких лет, без возможности попробовать решить их самостоятельно. Это и так слишком сложный проект для реализации. Если существуют такие проекты как skyline или citra, не нужно делать все проекты похожими на них.

**Comment by Fernandosin** [comment]
![IMG_20240105_011509](https://github.com/olegos2/mobox/assets/136645980/2ebe33b5-8330-4734-86cc-0ed710fb4bf8)
Can anyone give a clear answer and provide evidence? Where did they even find this application, because it is not on Github and 4Pda

**Comment by ilhan-athn7** [comment]
>...
 Can anyone give a clear answer and provide evidence? Where did they even find this application, because it is not on Github and 4Pda

The app Main activity shows the name of https://github.com/DotNetBurst
I guess he is the developer, maybe he did not release source code.

Anyway the virus report could be false positive, it is basically containing code for remote control ( Like someone is getting able to control your computer without letting you know. )

**Comment by DrakulaGonchik** [comment]
bros i had this backdoor rn i deleted it with antivirus.. so it means the hacker watched me all the time?

**Comment by ilhan-athn7** [comment]
> bros i had this backdoor rn i deleted it with antivirus.. so it means the hacker watched me all the time?

Antivirus software thinks InputBridge is a hidden RAT software controlled by someone far.

InputBridge is the tool being used as keyboard hardware replacement for running games on your phone.

It is most likely false positive, but we can't verify as no source code available.
