### ISSUE TITLE
mobox crashes right away when trying to launch games

### ISSUE THREAD

**Issue by beshoyay** [olegos2/mobox#67]
my phone is a realme 5 pro 4 gb version and when i am trying to launch anything like omori, lethal company, the forest mobox crashes

i know in a past issue someone had a similar issue and you said it's an issue because of low ram but can you add anything that forces mobox to not use anything past a specific amount of ram that the user chooses ? that might cause less crashes and makes it more convenient to use

might also add a shortcut option just like winlator does to make accessing games and programs easier

**Comment by Xsparkjimmy** [comment]
Bro I have same problem 1 week before I run gta 4 on my phone iqoo 7 sd870 processor but this time it gets stuck on new starting game page any thing could not open like gta san and not installing ultra iso.exe anyone have solution please tell me

**Comment by GrigoryNot2** [comment]
> ... can you add anything that forces mobox to not use anything past a specific amount of ram that the user chooses ?

Цель данного проекта - добиться максимума производительности. Зачем перетаскивать в него замедляющие функции из других проектов, пользуйтесь ими там.

> might also add a shortcut option just like winlator does to make accessing games and programs easier

Такая опция есть в wine, просто выдели правой кнопкой мыши exe файл игры и в меню выбери create link.

Не ленитесь изучать, уважайте чужой труд!

**Comment by GrigoryNot2** [comment]
> Bro I have same problem 1 week before I run gta 4 on my phone iqoo 7 sd870 processor but this time it gets stuck on new starting game page any thing could not open like gta san and not installing ultra iso.exe anyone have solution please tell me

Пробовал переустанавливать mobox? Или хотя бы контейнер wine?
