### ISSUE TITLE
Cdrom iso

### ISSUE THREAD

**Issue by MatejMagat305** [olegos2/mobox#7]
It is cool, but, is there some options for iso (f.e. zoo tycoon 1)?

**Comment by Snubbletoes** [comment]
Extract the iso or mdf to a folder. You can do this with WinRAR and probably other extraction programs/ apps. You can also use PowerISO to extract what's inside.

Name the folder (or folders) you extracted to as the same as the iso/ mdf you extracted from. You can also add the extension to the folder name, I have tried with adding it and without adding it, either way it works.

Inside a container go to the start menu and click run. Then enter "winecfg", go to Drives and click on E:\ (created a new one Z:\ and it still works the same). From here enter the path (or use "browse") to your folder you want to use as a mounted drive and click apply at the bottom right. At this point it will be mounted. (also set this drive in the advanced tab to CD-Rom).

Source: https://www.reddit.com/r/EmulationOnAndroid/comments/x13lhg/mount_iso_on_exagear_to_play_games_that_require/


for the last part i got to sdcard then downloads and the extracted folder. it worked for me. but i still get errors; "Unhandled exception!"
