### ISSUE TITLE
Games won't launch

### ISSUE THREAD

**Issue by veniamin456** [olegos2/mobox#72]
> After switching to lineage os, the games stopped launching, I tried CrDroid and Matrix on them and they also don’t launch, on miui everything started.
[mobox_log.txt](https://github.com/olegos2/mobox/files/13828922/mobox_log.txt)

**Comment by Fvrias** [comment]
I got too the error in log: sh: warning: setlocale: LC_ALL: cannot change locale (C.utf8)  and don't know how to fix it :(
