### ISSUE TITLE
Can't open display :0

### ISSUE THREAD

**Issue by Venvvs** [olegos2/mobox#8]
![Screenshot_20231206_190348_Termux](https://github.com/olegos2/mobox/assets/99629946/3fbfe3d5-268d-44ef-883f-1e2656aee966)

**Comment by Venvvs** [comment]
S23 Ultra

**Comment by Timbo303** [comment]
I have this issue too on my S21 so its probably samsung related. Heres my log for the App. Also note android 14 just arrived on my s21 today. 
[mobox_log.txt](https://github.com/olegos2/mobox/files/13591692/mobox_log.txt)

**Comment by Shrn744** [comment]
After install mobox 
Exit termux 
Enter again 
Run - 
"Pkg upgrade termux-x11-nightly"

This fix issue android 14

**Comment by 940842546** [comment]
> I have this issue too on my S21 so its probably samsung related. Heres my log for the App. Also note android 14 just arrived on my s21 today. [mobox_log.txt](https://github.com/olegos2/mobox/files/13591692/mobox_log.txt)

the same issue on MIUI and  "pkg upgrade termux-x11-nightly" solved it

**Comment by MNDL-27** [comment]
S24 ultra after installing its still the same
![Uploading Screenshot_20240619_112257_Termux.jpg…]()

**Comment by hay-guys** [comment]
try: 
pkg update
pkg install x11-repo
pkg install xorg-xhost
and after this turn off that
![Screenshot_20240807_150841_com hihonor systemmanager](https://github.com/user-attachments/assets/6dce10e1-8d7b-4b52-8e0c-1388e5339e82)
