### ISSUE TITLE
Termux X11 no connection

### ISSUE THREAD

**Issue by craankyinkyy** [olegos2/mobox#95]
Cant connect to termux x11 + cant open display 0? 

https://github.com/olegos2/mobox/assets/156167895/1b3b0517-61b2-45f3-bafc-16ae4691d09a

Please help

**Comment by Mwaid1** [comment]
Try killing termux and changing the settings a bit

**Comment by craankyinkyy** [comment]
Thanks, ill try on my way home

**Comment by craankyinkyy** [comment]
> Thanks, ill try on my way home

Nah still doesnt work

**Comment by Squid4572** [comment]
I also have this same exact issue

**Comment by NishantMajumdar** [comment]
bump

**Comment by linyaocrush** [comment]
我也遇到了这个问题

**Comment by Marius0402** [comment]
still not working mine too

**Comment by craankyinkyy** [comment]
https://github.com/termux/termux-x11/releases/tag/nightly

Download termux x11 from its official page

**Comment by AlexanderAlexis01** [comment]
> https://github.com/termux/termux-x11/releases/tag/nightly
> 
> Download termux x11 from its official page

u sure? i mean if u see the logs its cause it doesnt  load ths drivwrs

**Comment by craankyinkyy** [comment]
> > https://github.com/termux/termux-x11/releases/tag/nightly
> > Download termux x11 from its official page
> 
> u sure? i mean if u see the logs its cause it doesnt load ths drivwrs

I had the same issue, worked on mine idk🤔

**Comment by craankyinkyy** [comment]
Forgot that this was my thread

**Comment by AlexanderAlexis01** [comment]
> Forgot that this was my thread

omg it works, but it freezes after few seconds

**Comment by Flaymeyawn** [comment]
I dunno I have s21 plus 5g I d
Just want to be able to linix on this while I walk lol but i can't get Termux to open. Just says Not Connected was my Linux user ID to be used on one of these any help I'm not going to dig 50 pages.
