### ISSUE TITLE
Steam problems

### ISSUE THREAD

**Issue by NEFDSaul** [olegos2/mobox#99]
What is it ?
![Screenshot_2024-01-11-00-34-43-628_com termux x11](https://github.com/olegos2/mobox/assets/128971993/025ab1ad-b60e-4809-8bdc-180ccb575afb)

**Comment by PSzczepanski1996** [comment]
Use SteamExagear version from Box64Droid telegram channel:
https://t.me/box64droidchat
You can override files using 7zip.

**Comment by NEFDSaul** [comment]
> Use SteamExagear version from Box64Droid telegram channel:
> https://t.me/box64droidchat
> You can override files using 7zip.

Thnx , it works :)

**Comment by PSzczepanski1996** [comment]
If it works please close issue, thanks!
